import {useState} from "react";
import type {SavingsGoal} from "../models/goals";
import type {Currency} from "../models/finance";
import {formatCurrency} from "../calculations/finance";
interface Props{goals:SavingsGoal[];onAdd:(g:SavingsGoal)=>void;onAddSaved:(id:string,n:number)=>void;onDelete:(id:string)=>void;onClose:()=>void}
export function GoalsPanel({goals,onAdd,onAddSaved,onDelete,onClose}:Props){
 const [name,setName]=useState(""),[target,setTarget]=useState(""),[currency,setCurrency]=useState<Currency>("USD"),[deadline,setDeadline]=useState(""),[adding,setAdding]=useState<string|null>(null),[save,setSave]=useState("");
 function submit(e:React.FormEvent){e.preventDefault();if(!name.trim()||!target)return;onAdd({id:crypto.randomUUID(),name:name.trim(),target:Number(target),saved:0,currency,deadline:deadline||undefined,createdAt:new Date().toISOString()});setName("");setTarget("");setDeadline("")}
 return <div className="modal-backdrop"><div className="modal budget-modal"><div className="modal-header"><div><h2>🎯 أهداف الادخار</h2><span>خطط العائلة للمستقبل</span></div><button onClick={onClose}>×</button></div>
 <div className="goal-list">{goals.length===0&&<div className="empty-state">لا توجد أهداف ادخار بعد.</div>}{goals.map(g=>{const p=Math.min(100,g.saved/g.target*100);return <div className="goal-card" key={g.id}><div className="goal-head"><div><strong>{g.name}</strong><small>{g.deadline?`الهدف: ${g.deadline}`:"بدون موعد نهائي"}</small></div><button onClick={()=>onDelete(g.id)}>حذف</button></div><div className="goal-values"><span>{formatCurrency(g.saved,g.currency)}</span><strong>{formatCurrency(g.target,g.currency)}</strong></div><div className="goal-progress"><i style={{width:`${p}%`}}/></div><div className="goal-foot"><span>{Math.round(p)}% مكتمل</span><button onClick={()=>setAdding(g.id)}>＋ إضافة مبلغ</button></div>{adding===g.id&&<div className="goal-add"><input type="number" min="0" value={save} onChange={e=>setSave(e.target.value)} placeholder="المبلغ"/><button onClick={()=>{if(Number(save)>0){onAddSaved(g.id,Number(save));setSave("");setAdding(null)}}}>حفظ</button></div>}</div>})}</div>
 <h3 className="form-section-title">إنشاء هدف جديد</h3><form className="budget-form goal-form" onSubmit={submit}><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم الهدف"/><input type="number" min="0" value={target} onChange={e=>setTarget(e.target.value)} placeholder="المبلغ المستهدف"/><select value={currency} onChange={e=>setCurrency(e.target.value as Currency)}><option>SYP</option><option>USD</option><option>EUR</option></select><input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/><button>إنشاء</button></form><button className="secondary full-btn" onClick={onClose}>إغلاق</button>
 </div></div>
}