import {useEffect,useMemo,useState} from "react";
import {BalanceCircle} from "./components/BalanceCircle"; import {SummaryCard} from "./components/SummaryCard"; import {BottomNavigation} from "./components/BottomNavigation"; import {TransactionForm} from "./components/TransactionForm"; import {DebtForm} from "./components/DebtForm"; import {DebtPaymentForm} from "./components/DebtPaymentForm"; import {DebtList} from "./components/DebtList"; import {MonthlyChart} from "./components/MonthlyChart"; import {AssetCards} from "./components/AssetCards"; import {Reports} from "./components/Reports"; import {MemberManager} from "./components/MemberManager"; import {BudgetPanel} from "./components/BudgetPanel"; import type {Budget,Category} from "./models/budget"; import type {SavingsGoal,AlertSettings} from "./models/goals"; import {DEFAULT_ALERTS} from "./models/goals"; import {loadGoals,saveGoals,loadAlerts,saveAlerts} from "./services/goalsStorage"; import {GoalsPanel} from "./components/GoalsPanel"; import {AlertsPanel} from "./components/AlertsPanel"; import {DEFAULT_CATEGORIES} from "./models/budget"; import {loadCategories,saveCategories,loadBudgets,saveBudgets} from "./services/budgetStorage";
import type {Currency,Debt,DebtPayment,Transaction,ExchangeRates} from "./models/finance"; import {DEFAULT_RATES} from "./models/finance";
import {calculateBalances,formatCurrency,formatMoney,totalInCurrency} from "./calculations/finance"; import {remainingForDebt} from "./calculations/debts"; import {initializeStorage,loadRates,loadTransactions,saveRates,saveTransactions,loadDebts,saveDebts,loadDebtPayments,saveDebtPayments} from "./services/storage";
const seed:Transaction[]=[{id:"seed-1",type:"income",title:"راتب محمد",amount:5000000,currency:"SYP",date:"2026-08-27",createdAt:"2026-08-27T08:00:00Z"},{id:"seed-2",type:"expense",title:"مشتريات منزل",amount:250000,currency:"SYP",date:"2026-08-27",createdAt:"2026-08-27T09:00:00Z"},{id:"seed-3",type:"debt_receivable",title:"دين أحمد",amount:100,currency:"USD",date:"2026-08-26",person:"أحمد",createdAt:"2026-08-26T09:00:00Z"}];
function App(){
 const [currency,setCurrency]=useState<Currency>("USD"),[tx,setTx]=useState<Transaction[]>([]),[rates,setRates]=useState<ExchangeRates>(DEFAULT_RATES),[debts,setDebts]=useState<Debt[]>([]),[payments,setPayments]=useState<DebtPayment[]>([]);
 const [ready,setReady]=useState(false),[form,setForm]=useState<"income"|"expense"|null>(null),[debtForm,setDebtForm]=useState<"receivable"|"payable"|null>(null),[payDebt,setPayDebt]=useState<Debt|null>(null),[showDebts,setShowDebts]=useState(false),[showReports,setShowReports]=useState(false),[showMembers,setShowMembers]=useState(false),[members,setMembers]=useState<FamilyMember[]>([]),[currentMemberId,setCurrentMemberId]=useState(""),[showBudget,setShowBudget]=useState(false),[categories,setCategories]=useState<Category[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[goals,setGoals]=useState<SavingsGoal[]>([]),[alerts,setAlerts]=useState<AlertSettings>(DEFAULT_ALERTS),[showGoals,setShowGoals]=useState(false),[showAlerts,setShowAlerts]=useState(false);
 useEffect(()=>{initializeStorage().then(async()=>{const [t,r,d,p,ms,cs,bs,gs,as]=await Promise.all([loadTransactions(),loadRates(),loadDebts(),loadDebtPayments(),loadMembers(),loadCategories(),loadBudgets(),loadGoals(),loadAlerts()]);setTx(t.length?t:seed);setRates(r);setDebts(d);setPayments(p);let list=ms as FamilyMember[];if(!list.length){list=[{id:crypto.randomUUID(),name:"العائلة",role:"admin",createdAt:new Date().toISOString()}];await saveMembers(list)}setMembers(list);setCurrentMemberId(list[0]?.id||"");setCategories(cs.length?cs:DEFAULT_CATEGORIES);setBudgets(bs);setGoals(gs);setAlerts(as);setReady(true)})},[]);;;;
 useEffect(()=>{if(ready)void saveTransactions(tx)},[tx,ready]);useEffect(()=>{if(ready)void saveRates(rates)},[rates,ready]);useEffect(()=>{if(ready)void saveDebts(debts)},[debts,ready]);useEffect(()=>{if(ready)void saveDebtPayments(payments)},[payments,ready]);useEffect(()=>{if(ready)void saveMembers(members)},[members,ready]);useEffect(()=>{if(ready)void saveCategories(categories)},[categories,ready]);useEffect(()=>{if(ready)void saveBudgets(budgets)},[budgets,ready]);useEffect(()=>{if(ready)void saveGoals(goals)},[goals,ready]);useEffect(()=>{if(ready)void saveAlerts(alerts)},[alerts,ready]);
 const balances=useMemo(()=>calculateBalances(tx),[tx]);
 const income=tx.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expense=tx.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0);
 const receivable=debts.filter(d=>d.direction==="receivable").reduce((s,d)=>s+remainingForDebt(d,payments),0),payable=debts.filter(d=>d.direction==="payable").reduce((s,d)=>s+remainingForDebt(d,payments),0);
 const netWorth=totalInCurrency(balances,currency,rates), sym:Record<Currency,string>={SYP:"ل.س",USD:"$",EUR:"€"};
 function addTransaction(t:Transaction){setTx(v=>[...v,t])}
 function addDebt(d:Debt){setDebts(v=>[...v,d]);setTx(v=>[...v,{id:crypto.randomUUID(),type:d.direction==="receivable"?"debt_receivable":"debt_payable",title:`دين ${d.person}`,amount:d.originalAmount,currency:d.currency,date:d.date,person:d.person,notes:d.notes,createdAt:d.createdAt,debtId:d.id}])}
 function addPayment(p:DebtPayment){setPayments(v=>[...v,p]);const d=debts.find(x=>x.id===p.debtId);if(d)setTx(v=>[...v,{id:crypto.randomUUID(),type:d.direction==="receivable"?"debt_payment_receivable":"debt_payment_payable",title:`دفعة دين ${d.person}`,amount:p.amount,currency:d.currency,date:p.date,person:d.person,notes:p.notes,createdAt:p.createdAt,debtId:d.id}])}
 return <div className="app"><header className="topbar"><div><div className="brand">Z.Money</div><div className="subtitle">لوحة الإدارة المالية العائلية · v0.7</div></div><button className="profile-button" onClick={()=>setShowMembers(true)}>{members.find(m=>m.id===currentMemberId)?.name?.slice(0,1)||"م"}</button></header>
 <main className="content"><BalanceCircle currency={currency} balance={balances} rates={rates} onCurrencyChange={setCurrency}/>
 <div className="net-worth"><span>صافي السيولة الحالية</span><strong>{formatMoney(netWorth)} {sym[currency]}</strong><small>محسوب من جميع العمليات المسجلة</small></div>
 <div className="smart-summary"><div><strong>ملخص الشهر</strong><span>الدخل مقابل المصروف</span></div><b>{income-expense>=0?"فائض":"عجز"} {formatMoney(Math.abs(income-expense))} ل.س</b><small>{income>0?`نسبة المصروف من الدخل: ${Math.round(expense/income*100)}%`:"لم يسجل دخل بعد"}</small></div><div className="rate-box"><span>أسعار الصرف الحالية</span><strong>1 USD = {formatMoney(rates.USD_SYP)} ل.س</strong><strong>1 EUR = {formatMoney(rates.EUR_SYP)} ل.س</strong></div>
 <div className="quick-actions"><button className="quick income-btn" onClick={()=>setForm("income")}>＋ إضافة دخل</button><button className="quick expense-btn" onClick={()=>setForm("expense")}>－ إضافة مصروف</button></div>
 <div className="debt-actions"><button onClick={()=>setShowBudget(true)}>📊 الميزانية</button><button onClick={()=>setShowGoals(true)}>🎯 الادخار</button><button onClick={()=>setShowAlerts(true)}>🔔 التنبيهات</button><button onClick={()=>setDebtForm("receivable")}>＋ دين لي</button><button onClick={()=>setDebtForm("payable")}>＋ دين عليّ</button><button onClick={()=>setShowDebts(v=>!v)}>{showDebts?"إخفاء الديون":"إدارة الديون"}</button></div>
 <div className="summary-grid"><SummaryCard title="إجمالي الدخل" value={`${formatMoney(income)} ${sym.SYP}`} type="income"/><SummaryCard title="إجمالي المصروفات" value={`${formatMoney(expense)} ${sym.SYP}`} type="expense"/><SummaryCard title="لي ديون" value={`${formatMoney(receivable)} $`} type="receivable"/><SummaryCard title="عليّ ديون" value={`${formatMoney(payable)} $`} type="payable"/></div>
 <section className="assets-section"><div className="section-header"><h2>أرصدة العملات</h2><span>بعد العمليات</span></div><AssetCards balance={balances} rates={rates}/></section>
 <MonthlyChart transactions={tx} rates={rates}/>
 {showDebts&&<section className="debts-section"><div className="section-header"><h2>الديون</h2><span>{debts.length} دين</span></div><DebtList debts={debts} payments={payments} onPayment={setPayDebt}/></section>}
 <section className="transactions"><div className="section-header"><h2>آخر العمليات</h2><span>{tx.length} عملية</span></div><div className="transaction-list">{tx.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,12).map(t=><div className="transaction" key={t.id}><div className={`transaction-icon ${t.type==="expense"||t.type==="debt_payment_payable"?"expense-icon":t.type.startsWith("debt")?"debt-icon":"income-icon"}`}>{t.type==="expense"||t.type==="debt_payment_payable"?"↗":t.type.startsWith("debt")?"$":"↙"}</div><div className="transaction-info"><strong>{t.title}</strong><span>{t.date} · {t.category||t.person||"بدون تصنيف"}</span></div><strong className={t.type==="expense"||t.type==="debt_payment_payable"?"expense-text":"income-text"}>{t.type==="expense"||t.type==="debt_payment_payable"?"-":"+"}{formatCurrency(t.amount,t.currency)}</strong></div>)}</div></section></main>
 <BottomNavigation onIncome={()=>setForm("income")} onExpense={()=>setForm("expense")} onDebts={()=>setShowDebts(true)} onReports={()=>setShowReports(true)}/>
 {form&&<TransactionForm type={form} members={members} onSave={addTransaction} onClose={()=>setForm(null)}/>}
 {debtForm&&<DebtForm direction={debtForm} onSave={addDebt} onClose={()=>setDebtForm(null)}/>}
 {payDebt&&<DebtPaymentForm debt={payDebt} remaining={remainingForDebt(payDebt,payments)} onSave={addPayment} onClose={()=>setPayDebt(null)}/>}
 </div>
}
export default App;